# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [98]:
import pandas as pd
import time

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

### Part 1: Data Exploration ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

In [99]:
print(df.shape)

(891, 12)

In [100]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [101]:
df.info

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                                Heikkinen, Miss Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                        Graham, Miss Margaret Edith  female  19.0      0
888            Johnston, Miss Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [102]:
df.describe() #summary statistics

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [103]:
df.head(10) #head is used to return the first n rows where n is a variable passed

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### Part 2: Indexing and Selection ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

In [104]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                  Heikkinen, Miss Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                          Graham, Miss Margaret Edith
888              Johnston, Miss Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [105]:
df[["Name", "Sex", "Age", "Pclass"]]

                                                  Name     Sex   Age  Pclass
0                              Braund, Mr. Owen Harris    male  22.0       3
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0       1
2                                Heikkinen, Miss Laina  female  26.0       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0       1
4                             Allen, Mr. William Henry    male  35.0       3
..                                                 ...     ...   ...     ...
886                              Montvila, Rev. Juozas    male  27.0       2
887                        Graham, Miss Margaret Edith  female  19.0       1
888            Johnston, Miss Catherine Helen "Carrie"  female   NaN       3
889                              Behr, Mr. Karl Howell    male  26.0       1
890                                Dooley, Mr. Patrick    male  32.0       3

[891 rows x 4 columns]

In [106]:
s = time.time() # start time to calculate excution time

print(df.iloc[5]) # iloc return row by index

t = (time.time() - s) * 1e3 #time minus start time
print(round(t, 10), "ms") #print excution time up to 10 decimels

PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object
2.2449493408 ms

In [107]:
df.iloc[2:11, 3:10] # rows from index 2 to 10 and columns from index 3 to 9 cause iloc exclude the end index passed are 2:11 and 3:9

,Name,Sex,Age,SibSp,Parch,Ticket,Fare
2,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500
5,"Moran, Mr. James",male,NaN,0,0,330877,8.4583
6,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625
7,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333
9,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708
10,"Sandstrom, Miss Marguerite Rut",female,4.0,1,1,PP 9549,16.7000

### Part 3: Filtering ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

In [108]:
s = time.time() # start time to calculate excution time

print(df.loc[df["Age"] > 60]) #loc return selected rows based on the condtion age > 60

t = (time.time() - s) * 1e3 #time minus start time
print(round(t, 10), "ms") #print excution time up to 10 decimels

     PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H
54            55         0       1             Ostby, Mr. Engelhart Cornelius
96            97         0       1                  Goldschmidt, Mr. George B
116          117         0       3                       Connors, Mr. Patrick
170          171         0       1                  Van der hoef, Mr. Wyckoff
252          253         0       1                  Stead, Mr. William Thomas
275          276         1       1           Andrews, Miss Kornelia Theodosia
280          281         0       3                           Duane, Mr. Frank
326          327         0       3                  Nysveen, Mr. Johan Hansen
438          439         0       1                          Fortune, Mr. Mark
456          457         0       1                  Millet, Mr. Francis Davis
483          484         1       3                     Turkula, Mrs. (Hedwig)
493          494         0       1                    Artagaveytia, Mr. Ramon
545          546         0       1               Nicholson, Mr. Arthur Ernest
555          556         0       1                         Wright, Mr. George
570          571         1       2                         Harris, Mr. George
625          626         0       1                      Sutton, Mr. Frederick
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson
672          673         0       2                Mitchell, Mr. Henry Michael
745          746         0       1               Crosby, Capt. Edward Gifford
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)
851          852         0       3                        Svensson, Mr. Johan

        Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33     male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54     male  65.0      0      1       113509   61.9792          B30        C
96     male  71.0      0      0     PC 17754   34.6542           A5        C
116    male  70.5      0      0       370369    7.7500          NaN        Q
170    male  61.0      0      0       111240   33.5000          B19        S
252    male  62.0      0      0       113514   26.5500          C87        S
275  female  63.0      1      0        13502   77.9583           D7        S
280    male  65.0      0      0       336439    7.7500          NaN        Q
326    male  61.0      0      0       345364    6.2375          NaN        S
438    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456    male  65.0      0      0        13509   26.5500          E38        S
483  female  63.0      0      0         4134    9.5875          NaN        S
493    male  71.0      0      0     PC 17609   49.5042          NaN        C
545    male  64.0      0      0          693   26.0000          NaN        S
555    male  62.0      0      0       113807   26.5500          NaN        S
570    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625    male  61.0      0      0        36963   32.3208          D50        S
630    male  80.0      0      0        27042   30.0000          A23        S
672    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829  female  62.0      0      0       113572   80.0000          B28      NaN
851    male  74.0      0      0       347060    7.7750          NaN        S
17.2598361969 ms

In [109]:
df.loc[(df["Fare"] > 100) & (df["Pclass"] == 1)]  #loc return selected rows based on the condtion fare > 100 and class is first class

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

In [110]:
null_rows = df[df["Age"].isnull()] # isnull create a mask with true values for rows that have null in age applying this mask to thedata to identify null values
null_rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Part 4: Reindexing and Dropping ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

In [111]:
df_reverse = df.iloc[::-1]
df_reverse

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [112]:
df_drop= df.drop('Name', axis=1)
df_drop

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [113]:
df = df.dropna(subset=["Age"])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Part 5: Arithmetic and Data Alignment ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

In [114]:
df["Fare_Euros"] = df["Fare"] * 0.85
df

C:\Users\ELSAL\AppData\Local\Temp\ipykernel_13064\1901734789.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Fare_Euros"] = df["Fare"] * 0.85

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euros
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.162500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,60.590805
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.736250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.135000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.842500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,24.756250
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,11.050000
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,25.500000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,25.500000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,6.587500

In [115]:
s = time.time() # start time to calculate excution time

df_sub = df.copy()
df_sub["Age"] = df["Age"] - df["Age"].mean() # mean calculate the column mean then we subtract the mean from age values
print(df_sub)

t = (time.time() - s) * 1e3 #time minus start time
print(round(t, 10), "ms") #print excution time up to 10 decimels

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
885          886         0       3
886          887         0       2
887          888         1       1
889          890         1       1
890          891         0       3

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  -7.699118
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   8.300882
2                                Heikkinen, Miss Laina  female  -3.699118
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   5.300882
4                             Allen, Mr. William Henry    male   5.300882
..                                                 ...     ...        ...
885               Rice, Mrs. William (Margaret Norton)  female   9.300882
886                              Montvila, Rev. Juozas    male  -2.699118
887                        Graham, Miss Margaret Edith  female -10.699118
889                              Behr, Mr. Karl Howell    male  -3.699118
890                                Dooley, Mr. Patrick    male   2.300882

     SibSp  Parch            Ticket     Fare Cabin Embarked  Fare_Euros
0        1      0         A/5 21171   7.2500   NaN        S    6.162500
1        1      0          PC 17599  71.2833   C85        C   60.590805
2        0      0  STON/O2. 3101282   7.9250   NaN        S    6.736250
3        1      0            113803  53.1000  C123        S   45.135000
4        0      0            373450   8.0500   NaN        S    6.842500
..     ...    ...               ...      ...   ...      ...         ...
885      0      5            382652  29.1250   NaN        Q   24.756250
886      0      0            211536  13.0000   NaN        S   11.050000
887      0      0            112053  30.0000   B42        S   25.500000
889      0      0            111369  30.0000  C148        C   25.500000
890      0      0            370376   7.7500   NaN        Q    6.587500

[714 rows x 13 columns]
16.9477462769 ms

In [116]:
import numpy as np

new_array= np.random.randint(10, size=(df.shape[0])) # array the same size as number of rows has random values less than 10
print (new_array)
df_new = df
df_new[['Age', 'Fare']] = df_new[['Age', 'Fare']].sub(new_array, axis=0) # subtract the array from Age and Fare columns
df_new

[7 5 1 8 5 2 1 8 1 0 0 7 7 6 0 2 9 0 9 3 6 8 2 8 1 3 8 1 6 4 2 3 6 7 7 0 6
 1 5 7 4 7 7 3 2 5 7 5 5 0 3 2 9 2 2 8 7 5 5 0 4 0 7 1 0 8 8 8 7 4 8 6 8 8
 8 5 5 7 5 0 9 9 8 1 3 4 8 2 6 3 1 3 5 9 3 5 1 7 6 2 5 5 1 1 1 5 1 4 1 5 6
 3 4 0 3 7 2 4 9 2 7 1 3 4 0 2 1 9 6 1 2 2 3 7 6 0 9 9 2 6 6 1 2 0 9 6 8 3
 8 6 1 9 5 1 0 9 1 6 9 8 4 9 3 8 4 7 5 0 6 8 9 3 6 4 0 0 3 7 9 2 0 7 9 7 4
 4 9 1 7 4 3 1 3 2 8 2 6 3 3 0 8 2 9 0 2 0 4 8 8 4 6 1 5 6 8 4 9 1 9 5 0 2
 9 4 3 9 6 7 5 2 1 7 0 9 3 4 3 7 3 7 6 5 2 0 0 8 0 7 9 3 0 2 5 3 3 7 5 0 1
 0 7 5 4 8 9 2 8 5 6 3 9 0 1 0 0 7 2 8 9 7 2 4 3 0 4 4 3 1 6 4 9 8 7 0 3 0
 0 5 9 1 8 1 3 6 5 5 7 4 4 7 4 7 2 7 2 3 8 0 4 6 8 4 3 4 5 1 6 9 9 9 6 4 0
 3 6 2 1 3 5 0 1 2 2 2 4 6 2 4 5 3 3 8 2 3 8 3 9 7 9 1 5 2 5 0 3 1 4 8 7 1
 8 3 1 2 0 6 5 5 1 2 5 3 6 2 0 6 9 9 6 9 5 2 9 1 6 4 7 7 2 2 2 2 9 3 0 3 8
 7 5 7 3 7 0 8 7 6 1 4 0 5 5 9 7 1 7 8 6 9 6 0 3 0 1 8 0 2 6 9 1 1 7 7 4 1
 1 3 6 3 5 2 8 0 3 2 9 6 2 1 6 9 1 8 4 5 4 3 0 7 5 0 6 6 4 0 6 3 8 8 0 0 2
 0 2 4 8 6 0 2 5 0 9 1 4 4 0 5 6 5 0 4 8 2 1 7 1 5 4 2 5 2 1 2 7 5 7 0 9 4
 8 9 6 4 9 1 9 1 0 2 7 6 0 8 4 6 4 6 9 8 3 9 3 9 1 1 2 4 9 8 9 8 6 6 2 8 9
 6 2 1 2 1 6 1 4 1 4 7 8 7 8 1 5 6 9 7 4 6 6 0 9 3 4 0 1 8 5 5 5 8 9 2 0 6
 2 8 8 3 5 1 6 7 4 6 8 7 9 0 9 0 6 2 3 1 8 2 9 7 8 7 8 6 7 4 6 4 1 8 2 0 4
 4 5 4 0 6 5 7 8 3 8 7 8 2 7 6 7 7 4 2 2 4 4 1 8 2 9 6 1 4 3 3 1 5 9 3 3 6
 4 3 0 9 3 9 3 8 1 8 7 2 3 2 6 8 4 4 4 4 2 6 3 6 9 5 2 1 8 2 0 8 7 6 6 1 4
 1 2 3 9 5 1 6 1 5 1 9]

C:\Users\ELSAL\AppData\Local\Temp\ipykernel_13064\896153245.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[['Age', 'Fare']] = df_new[['Age', 'Fare']].sub(new_array, axis=0) # subtract the array from Age and Fare columns

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euros
0,1,0,3,"Braund, Mr. Owen Harris",male,15.0,1,0,A/5 21171,0.2500,NaN,S,6.162500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,33.0,1,0,PC 17599,66.2833,C85,C,60.590805
2,3,1,3,"Heikkinen, Miss Laina",female,25.0,0,0,STON/O2. 3101282,6.9250,NaN,S,6.736250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,27.0,1,0,113803,45.1000,C123,S,45.135000
4,5,0,3,"Allen, Mr. William Henry",male,30.0,0,0,373450,3.0500,NaN,S,6.842500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,33.0,0,5,382652,23.1250,NaN,Q,24.756250
886,887,0,2,"Montvila, Rev. Juozas",male,26.0,0,0,211536,12.0000,NaN,S,11.050000
887,888,1,1,"Graham, Miss Margaret Edith",female,14.0,0,0,112053,25.0000,B42,S,25.500000
889,890,1,1,"Behr, Mr. Karl Howell",male,25.0,0,0,111369,29.0000,C148,C,25.500000
890,891,0,3,"Dooley, Mr. Patrick",male,23.0,0,0,370376,-1.2500,NaN,Q,6.587500

### Part 6: Applying Functions ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

In [117]:
df["char_name"]= df["Name"].str.len() #str.len return number of characters 
df

C:\Users\ELSAL\AppData\Local\Temp\ipykernel_13064\1132122034.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["char_name"]= df["Name"].str.len() #str.len return number of characters

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euros,char_name
0,1,0,3,"Braund, Mr. Owen Harris",male,15.0,1,0,A/5 21171,0.2500,NaN,S,6.162500,23
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,33.0,1,0,PC 17599,66.2833,C85,C,60.590805,51
2,3,1,3,"Heikkinen, Miss Laina",female,25.0,0,0,STON/O2. 3101282,6.9250,NaN,S,6.736250,21
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,27.0,1,0,113803,45.1000,C123,S,45.135000,44
4,5,0,3,"Allen, Mr. William Henry",male,30.0,0,0,373450,3.0500,NaN,S,6.842500,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,33.0,0,5,382652,23.1250,NaN,Q,24.756250,36
886,887,0,2,"Montvila, Rev. Juozas",male,26.0,0,0,211536,12.0000,NaN,S,11.050000,21
887,888,1,1,"Graham, Miss Margaret Edith",female,14.0,0,0,112053,25.0000,B42,S,25.500000,27
889,890,1,1,"Behr, Mr. Karl Howell",male,25.0,0,0,111369,29.0000,C148,C,25.500000,21
890,891,0,3,"Dooley, Mr. Patrick",male,23.0,0,0,370376,-1.2500,NaN,Q,6.587500,19

In [118]:
df["diff"]= df["Fare"]-df["Age"]
df

C:\Users\ELSAL\AppData\Local\Temp\ipykernel_13064\1355571003.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["diff"]= df["Fare"]-df["Age"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euros,char_name,diff
0,1,0,3,"Braund, Mr. Owen Harris",male,15.0,1,0,A/5 21171,0.2500,NaN,S,6.162500,23,-14.7500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,33.0,1,0,PC 17599,66.2833,C85,C,60.590805,51,33.2833
2,3,1,3,"Heikkinen, Miss Laina",female,25.0,0,0,STON/O2. 3101282,6.9250,NaN,S,6.736250,21,-18.0750
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,27.0,1,0,113803,45.1000,C123,S,45.135000,44,18.1000
4,5,0,3,"Allen, Mr. William Henry",male,30.0,0,0,373450,3.0500,NaN,S,6.842500,24,-26.9500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,33.0,0,5,382652,23.1250,NaN,Q,24.756250,36,-9.8750
886,887,0,2,"Montvila, Rev. Juozas",male,26.0,0,0,211536,12.0000,NaN,S,11.050000,21,-14.0000
887,888,1,1,"Graham, Miss Margaret Edith",female,14.0,0,0,112053,25.0000,B42,S,25.500000,27,11.0000
889,890,1,1,"Behr, Mr. Karl Howell",male,25.0,0,0,111369,29.0000,C148,C,25.500000,21,4.0000
890,891,0,3,"Dooley, Mr. Patrick",male,23.0,0,0,370376,-1.2500,NaN,Q,6.587500,19,-24.2500

In [119]:
df.round(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euros,char_name,diff
0,1,0,3,"Braund, Mr. Owen Harris",male,15.0,1,0,A/5 21171,0.2,NaN,S,6.2,23,-14.8
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,33.0,1,0,PC 17599,66.3,C85,C,60.6,51,33.3
2,3,1,3,"Heikkinen, Miss Laina",female,25.0,0,0,STON/O2. 3101282,6.9,NaN,S,6.7,21,-18.1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,27.0,1,0,113803,45.1,C123,S,45.1,44,18.1
4,5,0,3,"Allen, Mr. William Henry",male,30.0,0,0,373450,3.1,NaN,S,6.8,24,-27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,33.0,0,5,382652,23.1,NaN,Q,24.8,36,-9.9
886,887,0,2,"Montvila, Rev. Juozas",male,26.0,0,0,211536,12.0,NaN,S,11.0,21,-14.0
887,888,1,1,"Graham, Miss Margaret Edith",female,14.0,0,0,112053,25.0,B42,S,25.5,27,11.0
889,890,1,1,"Behr, Mr. Karl Howell",male,25.0,0,0,111369,29.0,C148,C,25.5,21,4.0
890,891,0,3,"Dooley, Mr. Patrick",male,23.0,0,0,370376,-1.2,NaN,Q,6.6,19,-24.2

### Part 7: Mapping and Transformation ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

In [120]:
df_recode= df.copy()
df_recode["Sex"].replace(['female', 'male'], [0, 1], inplace=True)
df_recode

C:\Users\ELSAL\AppData\Local\Temp\ipykernel_13064\2293170232.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_recode["Sex"].replace(['female', 'male'], [0, 1], inplace=True)
C:\Users\ELSAL\AppData\Local\Temp\ipykernel_13064\2293170232.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_recode["Sex"].replace(['female', 'male'], [0, 1], inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euros,char_name,diff
0,1,0,3,"Braund, Mr. Owen Harris",1,15.0,1,0,A/5 21171,0.2500,NaN,S,6.162500,23,-14.7500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,33.0,1,0,PC 17599,66.2833,C85,C,60.590805,51,33.2833
2,3,1,3,"Heikkinen, Miss Laina",0,25.0,0,0,STON/O2. 3101282,6.9250,NaN,S,6.736250,21,-18.0750
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,27.0,1,0,113803,45.1000,C123,S,45.135000,44,18.1000
4,5,0,3,"Allen, Mr. William Henry",1,30.0,0,0,373450,3.0500,NaN,S,6.842500,24,-26.9500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",0,33.0,0,5,382652,23.1250,NaN,Q,24.756250,36,-9.8750
886,887,0,2,"Montvila, Rev. Juozas",1,26.0,0,0,211536,12.0000,NaN,S,11.050000,21,-14.0000
887,888,1,1,"Graham, Miss Margaret Edith",0,14.0,0,0,112053,25.0000,B42,S,25.500000,27,11.0000
889,890,1,1,"Behr, Mr. Karl Howell",1,25.0,0,0,111369,29.0000,C148,C,25.500000,21,4.0000
890,891,0,3,"Dooley, Mr. Patrick",1,23.0,0,0,370376,-1.2500,NaN,Q,6.587500,19,-24.2500

In [121]:
def age_category(age): # function that takes age as var and return a category depending on the value 
    if age < 18: #if age less than 18 category is a child
        return "child"
    elif 18 <= age < 70: #if age more than 18 and less than 70 category is a adult
        return "adult"
    else: # more than 70 category is senior
        return "senior"
df["age_category"] = df["Age"].map(age_category) #map is used here to apply the function to every value in the age column
df

C:\Users\ELSAL\AppData\Local\Temp\ipykernel_13064\1814374101.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["age_category"] = df["Age"].map(age_category) #map is used here to apply the function to every value in the age column

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euros,char_name,diff,age_category
0,1,0,3,"Braund, Mr. Owen Harris",male,15.0,1,0,A/5 21171,0.2500,NaN,S,6.162500,23,-14.7500,child
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,33.0,1,0,PC 17599,66.2833,C85,C,60.590805,51,33.2833,adult
2,3,1,3,"Heikkinen, Miss Laina",female,25.0,0,0,STON/O2. 3101282,6.9250,NaN,S,6.736250,21,-18.0750,adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,27.0,1,0,113803,45.1000,C123,S,45.135000,44,18.1000,adult
4,5,0,3,"Allen, Mr. William Henry",male,30.0,0,0,373450,3.0500,NaN,S,6.842500,24,-26.9500,adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,33.0,0,5,382652,23.1250,NaN,Q,24.756250,36,-9.8750,adult
886,887,0,2,"Montvila, Rev. Juozas",male,26.0,0,0,211536,12.0000,NaN,S,11.050000,21,-14.0000,adult
887,888,1,1,"Graham, Miss Margaret Edith",female,14.0,0,0,112053,25.0000,B42,S,25.500000,27,11.0000,child
889,890,1,1,"Behr, Mr. Karl Howell",male,25.0,0,0,111369,29.0000,C148,C,25.500000,21,4.0000,adult
890,891,0,3,"Dooley, Mr. Patrick",male,23.0,0,0,370376,-1.2500,NaN,Q,6.587500,19,-24.2500,adult

### Part 8 ###
1. Select a single row from the dataset.
2. Show only the rows where the age is above 60.
3. Subtract the average age from every age value.

**given that the list is in the hunderards the size is relatively small so list excution time is less than pandas here**

*for example in number 2 pandas is 17.2598361969 ms vs 0.6024837494 ms in lists*

In [122]:
data_list = df.values.tolist() # convert the dataframe to a nested list (list of lists)
data_list

[[1,
  0,
  3,
  'Braund, Mr. Owen Harris',
  'male',
  15.0,
  1,
  0,
  'A/5 21171',
  0.25,
  nan,
  'S',
  6.1625,
  23,
  -14.75,
  'child'],
 [2,
  1,
  1,
  'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'female',
  33.0,
  1,
  0,
  'PC 17599',
  66.2833,
  'C85',
  'C',
  60.590804999999996,
  51,
  33.2833,
  'adult'],
 [3,
  1,
  3,
  'Heikkinen, Miss Laina',
  'female',
  25.0,
  0,
  0,
  'STON/O2. 3101282',
  6.925,
  nan,
  'S',
  6.73625,
  21,
  -18.075,
  'adult'],
 [4,
  1,
  1,
  'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
  'female',
  27.0,
  1,
  0,
  '113803',
  45.1,
  'C123',
  'S',
  45.135,
  44,
  18.1,
  'adult'],
 [5,
  0,
  3,
  'Allen, Mr. William Henry',
  'male',
  30.0,
  0,
  0,
  '373450',
  3.0500000000000007,
  nan,
  'S',
  6.8425,
  24,
  -26.95,
  'adult'],
 [7,
  0,
  1,
  'McCarthy, Mr. Timothy J',
  'male',
  52.0,
  0,
  0,
  '17463',
  49.8625,
  'E46',
  'S',
  44.083124999999995,
  23,
  -2.137500000000003,
  'adult'],
 [8,
  0,
  3,
  'Palsson, Master Gosta Leonard',
  'male',
  1.0,
  3,
  1,
  '349909',
  20.075,
  nan,
  'S',
  17.91375,
  29,
  19.075,
  'child'],
 [9,
  1,
  3,
  'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
  'female',
  19.0,
  0,
  2,
  '347742',
  3.1333,
  nan,
  'S',
  9.463305,
  49,
  -15.8667,
  'adult'],
 [10,
  1,
  2,
  'Nasser, Mrs. Nicholas (Adele Achem)',
  'female',
  13.0,
  1,
  0,
  '237736',
  29.0708,
  nan,
  'C',
  25.56018,
  35,
  16.0708,
  'child'],
 [11,
  1,
  3,
  'Sandstrom, Miss Marguerite Rut',
  'female',
  4.0,
  1,
  1,
  'PP 9549',
  16.7,
  'G6',
  'S',
  14.194999999999999,
  30,
  12.7,
  'child'],
 [12,
  1,
  1,
  'Bonnell, Miss Elizabeth',
  'female',
  58.0,
  0,
  0,
  '113783',
  26.55,
  'C103',
  'S',
  22.5675,
  23,
  -31.45,
  'adult'],
 [13,
  0,
  3,
  'Saundercock, Mr. William Henry',
  'male',
  13.0,
  0,
  0,
  'A/5. 2151',
  1.0500000000000007,
  nan,
  'S',
  6.8425,
  30,
  -11.95,
  'child'],
 [14,
  0,
  3,
  'Andersson, Mr. Anders Johan',
  'male',
  32.0,
  1,
  5,
  '347082',
  24.275,
  nan,
  'S',
  26.58375,
  27,
  -7.725000000000001,
  'adult'],
 [15,
  0,
  3,
  'Vestrom, Miss Hulda Amanda Adolfina',
  'female',
  8.0,
  0,
  0,
  '350406',
  1.8541999999999996,
  nan,
  'S',
  6.676069999999999,
  35,
  -6.1458,
  'child'],
 [16,
  1,
  2,
  'Hewlett, Mrs. (Mary D Kingcome) ',
  'female',
  55.0,
  0,
  0,
  '248706',
  16.0,
  nan,
  'S',
  13.6,
  32,
  -39.0,
  'adult'],
 [17,
  0,
  3,
  'Rice, Master Eugene',
  'male',
  0.0,
  4,
  1,
  '382652',
  27.125,
  nan,
  'Q',
  24.756249999999998,
  19,
  27.125,
  'child'],
 [19,
  0,
  3,
  'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
  'female',
  22.0,
  1,
  0,
  '345763',
  9.0,
  nan,
  'S',
  15.299999999999999,
  55,
  -13.0,
  'adult'],
 [21,
  0,
  2,
  'Fynney, Mr. Joseph J',
  'male',
  35.0,
  0,
  0,
  '239865',
  26.0,
  nan,
  'S',
  22.099999999999998,
  20,
  -9.0,
  'adult'],
 [22,
  1,
  2,
  'Beesley, Mr. Lawrence',
  'male',
  25.0,
  0,
  0,
  '248698',
  4.0,
  'D56',
  'S',
  11.049999999999999,
  21,
  -21.0,
  'adult'],
 [23,
  1,
  3,
  'McGowan, Miss Anna "Annie"',
  'female',
  12.0,
  0,
  0,
  '330923',
  5.0291999999999994,
  nan,
  'Q',
  6.824819999999999,
  26,
  -6.9708000000000006,
  'child'],
 [24,
  1,
  1,
  'Sloper, Mr. William Thompson',
  'male',
  22.0,
  0,
  0,
  '113788',
  29.5,
  'A6',
  'S',
  30.175,
  28,
  7.5,
  'adult'],
 [25,
  0,
  3,
  'Palsson, Miss Torborg Danira',
  'female',
  0.0,
  3,
  1,
  '349909',
  13.075,
  nan,
  'S',
  17.91375,
  28,
  13.075,
  'child'],
 [26,
  1,
  3,
  'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
  'female',
  36.0,
  1,
  5,
  '347077',
  29.3875,
  nan,
  'S',
  26.679375,
  57,
  -6.612500000000001,
  'adult'],
 [28,
  0,
  1,
  'Fortune, Mr. Charles Alexander',
  'male',
  11.0,
  3,
  2,
  '19950',
  255.0,
  'C23 C25 C27',
  'S',
  223.54999999999998,
  30,
  244.0,
  'child'],
 [31,
  0,
  1,
  'Uruchurtu, Don. Manuel E',
  'male',
  39.0,
  0,
  0,
  'PC 17601',
  26.7208,
  nan,
  'C',
  23.56268,
  24,
  -12.2792,
  'adult'],
 [34,
  0,
  2,
  'Wheadon, Mr. Edward H',
  'male',
  63.0,
  0,
  0,
  'C.A. 24579',
  7.5,
  nan,
  'S',
  8.924999999999999,
  21,
  -55.5,
  'adult'],
 [35,
  0,
  1,
  'Meyer, Mr. Edgar Joseph',
  'male',
  20.0,
  1,
  0,
  'PC 17604',
  74.1708,
  nan,
  'C',
  69.84518,
  23,
  54.1708,
  'adult'],
 [36,
  0,
  1,
  'Holverson, Mr. Alexander Oskar',
  'male',
  41.0,
  1,
  0,
  '113789',
  51.0,
  nan,
  'S',
  44.199999999999996,
  30,
  10.0,
  'adult'],
 [38,
  0,
  3,
  'Cann, Mr. Ernest Charles',
  'male',
  15.0,
  0,
  0,
  'A./5. 2152',
  2.0500000000000007,
  nan,
  'S',
  6.8425,
  24,
  -12.95,
  'child'],
 [39,
  0,
  3,
  'Vander Planke, Miss Augusta Maria',
  'female',
  14.0,
  2,
  0,
  '345764',
  14.0,
  nan,
  'S',
  15.299999999999999,
  33,
  0.0,
  'child'],
 [40,
  1,
  3,
  'Nicola-Yarred, Miss Jamila',
  'female',
  12.0,
  1,
  0,
  '2651',
  9.2417,
  nan,
  'C',
  9.555444999999999,
  26,
  -2.7583,
  'child'],
 [41,
  0,
  3,
  'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
  'female',
  37.0,
  1,
  0,
  '7546',
  6.475,
  nan,
  'S',
  8.053749999999999,
  46,
  -30.525,
  'adult'],
 [42,
  0,
  2,
  'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
  'female',
  21.0,
  1,
  0,
  '11668',
  15.0,
  nan,
  'S',
  17.849999999999998,
  56,
  -6.0,
  'adult'],
 [44,
  1,
  2,
  'Laroche, Miss Simonne Marie Anne Andree',
  'female',
  -4.0,
  1,
  2,
  'SC/Paris 2123',
  34.5792,
  nan,
  'C',
  35.34232,
  39,
  38.5792,
  'child'],
 [45,
  1,
  3,
  'Devaney, Miss Margaret Delia',
  'female',
  12.0,
  0,
  0,
  '330958',
  0.8792,
  nan,
  'Q',
  6.6973199999999995,
  28,
  -11.1208,
  'child'],
 [50,
  0,
  3,
  'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
  'female',
  18.0,
  1,
  0,
  '349237',
  17.8,
  nan,
  'S',
  15.13,
  45,
  -0.1999999999999993,
  'adult'],
 [51,
  0,
  3,
  'Panula, Master Juha Niilo',
  'male',
  1.0,
  4,
  1,
  '3101295',
  33.6875,
  nan,
  'S',
  33.734375,
  25,
  32.6875,
  'child'],
 [52,
  0,
  3,
  'Nosworthy, Mr. Richard Cater',
  'male',
  20.0,
  0,
  0,
  'A/4. 39886',
  6.8,
  nan,
  'S',
  6.63,
  28,
  -13.2,
  'adult'],
 [53,
  1,
  1,
  'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
  'female',
  44.0,
  1,
  0,
  'PC 17572',
  71.7292,
  'D33',
  'C',
  65.21982,
  40,
  27.729200000000006,
  'adult'],
 [54,
  1,
  2,
  'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
  'female',
  22.0,
  1,
  0,
  '2926',
  19.0,
  nan,
  'S',
  22.099999999999998,
  50,
  -3.0,
  'adult'],
 [55,
  0,
  1,
  'Ostby, Mr. Engelhart Cornelius',
  'male',
  61.0,
  0,
  1,
  '113509',
  57.9792,
  'B30',
  'C',
  52.68232,
  30,
  -3.0208000000000013,
  'adult'],
 [57,
  1,
  2,
  'Rugg, Miss Emily',
  'female',
  14.0,
  0,
  0,
  'C.A. 31026',
  3.5,
  nan,
  'S',
  8.924999999999999,
  16,
  -10.5,
  'child'],
 [58,
  0,
  3,
  'Novel, Mr. Mansouer',
  'male',
  21.5,
  0,
  0,
  '2697',
  0.22919999999999963,
  nan,
  'C',
  6.144819999999999,
  19,
  -21.2708,
  'adult'],
 [59,
  1,
  2,
  'West, Miss Constance Mirium',
  'female',
  2.0,
  1,
  2,
  'C.A. 34651',
  24.75,
  nan,
  'S',
  23.5875,
  27,
  22.75,
  'child'],
 [60,
  0,
  3,
  'Goodwin, Master William Frederick',
  'male',
  9.0,
  5,
  2,
  'CA 2144',
  44.9,
  nan,
  'S',
  39.864999999999995,
  33,
  35.9,
  'child'],
 [61,
  0,
  3,
  'Sirayanian, Mr. Orsen',
  'male',
  17.0,
  0,
  0,
  '2669',
  2.2291999999999996,
  nan,
  'C',
  6.144819999999999,
  21,
  -14.770800000000001,
  'child'],
 [62,
  1,
  1,
  'Icard, Miss Amelie',
  'female',
  31.0,
  0,
  0,
  '113572',
  73.0,
  'B28',
  nan,
  68.0,
  18,
  42.0,
  'adult'],
 [63,
  0,
  1,
  'Harris, Mr. Henry Birkhardt',
  'male',
  40.0,
  1,
  0,
  '36973',
  78.475,
  'C83',
  'S',
  70.95375,
  27,
  38.474999999999994,
  'adult'],
 [64,
  0,
  3,
  'Skoog, Master Harald',
  'male',
  -1.0,
  3,
  2,
  '347088',
  22.9,
  nan,
  'S',
  23.715,
  20,
  23.9,
  'child'],
 [67,
  1,
  2,
  'Nye, Mrs. (Elizabeth Ramell)',
  'female',
  29.0,
  0,
  0,
  'C.A. 29395',
  10.5,
  'F33',
  'S',
  8.924999999999999,
  28,
  -18.5,
  'adult'],
 [68,
  0,
  3,
  'Crease, Mr. Ernest James',
  'male',
  16.0,
  0,
  0,
  'S.P. 3464',
  5.1583000000000006,
  nan,
  'S',
  6.9345550000000005,
  24,
  -10.8417,
  'child'],
 [69,
  1,
  3,
  'Andersson, Miss Erna Alexandra',
  'female',
  15.0,
  4,
  2,
  '3101281',
  5.925,
  nan,
  'S',
  6.73625,
  30,
  -9.075,
  'child'],
 [70,
  0,
  3,
  'Kink, Mr. Vincenz',
  'male',
  17.0,
  2,
  0,
  '315151',
  -0.33750000000000036,
  nan,
  'S',
  7.363124999999999,
  17,
  -17.3375,
  'child'],
 [71,
  0,
  2,
  'Jenkin, Mr. Stephen Curnow',
  'male',
  30.0,
  0,
  0,
  'C.A. 33111',
  8.5,
  nan,
  'S',
  8.924999999999999,
  26,
  -21.5,
  'adult'],
 [72,
  0,
  3,
  'Goodwin, Miss Lillian Amy',
  'female',
  14.0,
  5,
  2,
  'CA 2144',
  44.9,
  nan,
  'S',
  39.864999999999995,
  25,
  30.9,
  'child'],
 [73,
  0,
  2,
  'Hood, Mr. Ambrose Jr',
  'male',
  13.0,
  0,
  0,
  'S.O.C. 14879',
  65.5,
  nan,
  'S',
  62.475,
  20,
  52.5,
  'child'],
 [74,
  0,
  3,
  'Chronopoulos, Mr. Apostolos',
  'male',
  19.0,
  1,
  0,
  '2680',
  7.4542,
  nan,
  'C',
  12.28607,
  27,
  -11.5458,
  'adult'],
 [75,
  1,
  3,
  'Bing, Mr. Lee',
  'male',
  27.0,
  0,
  0,
  '1601',
  51.4958,
  nan,
  'S',
  48.02143,
  13,
  24.495800000000003,
  'adult'],
 [76,
  0,
  3,
  'Moen, Mr. Sigurd Hansen',
  'male',
  20.0,
  0,
  0,
  '348123',
  2.6500000000000004,
  'F G73',
  'S',
  6.5025,
  23,
  -17.35,
  'adult'],
 [79,
  1,
  2,
  'Caldwell, Master Alden Gates',
  'male',
  0.83,
  0,
  2,
  '248738',
  29.0,
  nan,
  'S',
  24.65,
  28,
  28.17,
  'child'],
 [80,
  1,
  3,
  'Dowdell, Miss Elizabeth',
  'female',
  26.0,
  0,
  0,
  '364516',
  8.475,
  nan,
  'S',
  10.60375,
  23,
  -17.525,
  'adult'],
 [81,
  0,
  3,
  'Waelens, Mr. Achille',
  'male',
  22.0,
  0,
  0,
  '345767',
  9.0,
  nan,
  'S',
  7.6499999999999995,
  20,
  -13.0,
  'adult'],
 [82,
  1,
  3,
  'Sheerlinck, Mr. Jan Baptist',
  'male',
  22.0,
  0,
  0,
  '345779',
  2.5,
  nan,
  'S',
  8.075,
  27,
  -19.5,
  'adult'],
 [84,
  0,
  1,
  'Carrau, Mr. Francisco M',
  'male',
  27.0,
  0,
  0,
  '113059',
  46.1,
  nan,
  'S',
  40.035000000000004,
  23,
  19.1,
  'adult'],
 [85,
  1,
  2,
  'Ilett, Miss Bertha',
  'female',
  17.0,
  0,
  0,
  'SO/C 14885',
  10.5,
  nan,
  'S',
  8.924999999999999,
  18,
  -6.5,
  'child'],
 [86,
  1,
  3,
  'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
  'female',
  25.0,
  3,
  0,
  '3101278',
  7.85,
  nan,
  'S',
  13.4725,
  55,
  -17.15,
  'adult'],
 [87,
  0,
  3,
  'Ford, Mr. William Neal',
  'male',
  8.0,
  1,
  3,
  'W./C. 6608',
  26.375,
  nan,
  'S',
  29.21875,
  22,
  18.375,
  'child'],
 [89,
  1,
  1,
  'Fortune, Miss Mabel Helen',
  'female',
  15.0,
  3,
  2,
  '19950',
  255.0,
  'C23 C25 C27',
  'S',
  223.54999999999998,
  25,
  240.0,
  'child'],
 [90,
  0,
  3,
  'Celotti, Mr. Francesco',
  'male',
  17.0,
  0,
  0,
  '343275',
  1.0500000000000007,
  nan,
  'S',
  6.8425,
  22,
  -15.95,
  'child'],
 [91,
  0,
  3,
  'Christmann, Mr. Emil',
  'male',
  25.0,
  0,
  0,
  '343276',
  4.050000000000001,
  nan,
  'S',
  6.8425,
  20,
  -20.95,
  'adult'],
 [92,
  0,
  3,
  'Andreasson, Mr. Paul Edvin',
  'male',
  12.0,
  0,
  0,
  '347466',
  -0.14580000000000037,
  nan,
  'S',
  6.676069999999999,
  26,
  -12.145800000000001,
  'child'],
 [93,
  0,
  1,
  'Chaffee, Mr. Herbert Fuller',
  'male',
  40.0,
  1,
  0,
  'W.E.P. 5734',
  55.175,
  'E31',
  'S',
  51.998749999999994,
  27,
  15.174999999999997,
  'adult'],
 [94,
  0,
  3,
  'Dean, Mr. Bertram Frank',
  'male',
  18.0,
  1,
  2,
  'C.A. 2315',
  12.575,
  nan,
  'S',
  17.48875,
  23,
  -5.425000000000001,
  'adult'],
 [95,
  0,
  3,
  'Coxon, Mr. Daniel',
  'male',
  51.0,
  0,
  0,
  '364500',
  -0.75,
  nan,
  'S',
  6.1625,
  17,
  -51.75,
  'adult'],
 [97,
  0,
  1,
  'Goldschmidt, Mr. George B',
  'male',
  63.0,
  0,
  0,
  'PC 17754',
  26.654200000000003,
  'A5',
  'C',
  29.45607,
  25,
  -36.3458,
  'adult'],
 [98,
  1,
  1,
  'Greenfield, Mr. William Bertram',
  'male',
  18.0,
  0,
  1,
  'PC 17759',
  58.3583,
  'D10 D12',
  'C',
  53.854555,
  31,
  40.3583,
  'adult'],
 [99,
  1,
  2,
  'Doling, Mrs. John T (Ada Julia Bone)',
  'female',
  29.0,
  0,
  1,
  '231919',
  18.0,
  nan,
  'S',
  19.55,
  36,
  -11.0,
  'adult'],
 [100,
  0,
  2,
  'Kantor, Mr. Sinai',
  'male',
  27.0,
  1,
  0,
  '244367',
  19.0,
  nan,
  'S',
  22.099999999999998,
  17,
  -8.0,
  'adult'],
 [101,
  0,
  3,
  'Petranec, Miss Matilda',
  'female',
  23.0,
  0,
  0,
  '349245',
  2.8958000000000004,
  nan,
  'S',
  6.71143,
  22,
  -20.1042,
  'adult'],
 [103,
  0,
  1,
  'White, Mr. Richard Frasar',
  'male',
  21.0,
  0,
  1,
  '35281',
  77.2875,
  'D26',
  'S',
  65.694375,
  25,
  56.287499999999994,
  'adult'],
 [104,
  0,
  3,
  'Johansson, Mr. Gustaf Joel',
  'male',
  24.0,
  0,
  0,
  '7540',
  -0.34580000000000055,
  nan,
  'S',
  7.356069999999999,
  26,
  -24.3458,
  'adult'],
 [105,
  0,
  3,
  'Gustafsson, Mr. Anders Vilhelm',
  'male',
  28.0,
  2,
  0,
  '3101276',
  -1.0750000000000002,
  nan,
  'S',
  6.73625,
  30,
  -29.075,
  'adult'],
 [106,
  0,
  3,
  'Mionoff, Mr. Stoytcho',
  'male',
  20.0,
  0,
  0,
  '349207',
  -0.10419999999999963,
  nan,
  'S',
  6.71143,
  21,
  -20.1042,
  'adult'],
 [107,
  1,
  3,
  'Salkjelsvik, Miss Anna Kristine',
  'female',
  20.0,
  0,
  0,
  '343120',
  6.65,
  nan,
  'S',
  6.5025,
  31,
  -13.35,
  'adult'],
 [109,
  0,
  3,
  'Rekic, Mr. Tido',
  'male',
  35.0,
  0,
  0,
  '349249',
  4.8958,
  nan,
  'S',
  6.71143,
  15,
  -30.1042,
  'adult'],
 [111,
  0,
  1,
  'Porter, Mr. Walter Chamberlain',
  'male',
  43.0,
  0,
  0,
  '110465',
  48.0,
  'C110',
  'S',
  44.199999999999996,
  30,
  5.0,
  'adult'],
 [112,
  0,
  3,
  'Zabour, Miss Hileni',
  'female',
  6.5,
  1,
  0,
  '2665',
  6.4542,
  nan,
  'C',
  12.28607,
  19,
  -0.04579999999999984,
  'child'],
 [113,
  0,
  3,
  'Barton, Mr. David John',
  'male',
  20.0,
  0,
  0,
  '324669',
  6.050000000000001,
  nan,
  'S',
  6.8425,
  22,
  -13.95,
  'adult'],
 [114,
  0,
  3,
  'Jussila, Miss Katriina',
  'female',
  14.0,
  1,
  0,
  '4136',
  3.8249999999999993,
  nan,
  'S',
  8.351249999999999,
  22,
  -10.175,
  'child'],
 [115,
  0,
  3,
  'Attalah, Miss Malake',
  'female',
  14.0,
  0,
  0,
  '2627',
  11.4583,
  nan,
  'C',
  12.289555,
  20,
  -2.5417000000000005,
  'child'],
 [116,
  0,
  3,
  'Pekoniemi, Mr. Edvard',
  'male',
  20.0,
  0,
  0,
  'STON/O 2. 3101294',
  6.925,
  nan,
  'S',
  6.73625,
  21,
  -13.075,
  'adult'],
 [117,
  0,
  3,
  'Connors, Mr. Patrick',
  'male',
  67.5,
  0,
  0,
  '370369',
  4.75,
  nan,
  'Q',
  6.5874999999999995,
  20,
  -62.75,
  'adult'],
 [118,
  0,
  2,
  'Turpin, Mr. William John Robert',
  'male',
  24.0,
  1,
  0,
  '11668',
  16.0,
  nan,
  'S',
  17.849999999999998,
  31,
  -8.0,
  'adult'],
 [119,
  0,
  1,
  'Baxter, Mr. Quigg Edmond',
  'male',
  15.0,
  0,
  1,
  'PC 17558',
  238.5208,
  'B58 B60',
  'C',
  210.39268,
  24,
  223.5208,
  'child'],
 [120,
  0,
  3,
  'Andersson, Miss Ellis Anna Maria',
  'female',
  -1.0,
  4,
  2,
  '347082',
  28.275,
  nan,
  'S',
  26.58375,
  32,
  29.275,
  'child'],
 [121,
  0,
  2,
  'Hickman, Mr. Stanley George',
  'male',
  16.0,
  2,
  0,
  'S.O.C. 14879',
  68.5,
  nan,
  'S',
  62.475,
  27,
  52.5,
  'child'],
 [123,
  0,
  2,
  'Nasser, Mr. Nicholas',
  'male',
  31.5,
  1,
  0,
  '237736',
  29.0708,
  nan,
  'C',
  25.56018,
  20,
  -2.4292000000000016,
  'adult'],
 [124,
  1,
  2,
  'Webber, Miss Susan',
  'female',
  25.5,
  0,
  0,
  '27267',
  6.0,
  'E101',
  'S',
  11.049999999999999,
  18,
  -19.5,
  'adult'],
 [125,
  0,
  1,
  'White, Mr. Percival Wayland',
  'male',
  48.0,
  0,
  1,
  '35281',
  71.2875,
  'D26',
  'S',
  65.694375,
  27,
  23.287499999999994,
  'adult'],
 [126,
  1,
  3,
  'Nicola-Yarred, Master Elias',
  'male',
  10.0,
  1,
  0,
  '2651',
  9.2417,
  nan,
  'C',
  9.555444999999999,
  27,
  -0.7583000000000002,
  'child'],
 [128,
  1,
  3,
  'Madsen, Mr. Fridtjof Arne',
  'male',
  19.0,
  0,
  0,
  'C 17369',
  2.1417,
  nan,
  'S',
  6.070445,
  25,
  -16.8583,
  'adult'],
 [130,
  0,
  3,
  'Ekstrom, Mr. Johan',
  'male',
  40.0,
  0,
  0,
  '347061',
  1.9749999999999996,
  nan,
  'S',
  5.92875,
  18,
  -38.025,
  'adult'],
 [131,
  0,
  3,
  'Drazenoic, Mr. Jozef',
  'male',
  32.0,
  0,
  0,
  '349241',
  6.8958,
  nan,
  'C',
  6.71143,
  20,
  -25.1042,
  'adult'],
 [132,
  0,
  3,
  'Coelho, Mr. Domingos Fernandeo',
  'male',
  19.0,
  0,
  0,
  'SOTON/O.Q. 3101307',
  6.05,
  nan,
  'S',
  5.9925,
  30,
  -12.95,
  'adult'],
 [133,
  0,
  3,
  'Robins, Mrs. Alexander A (Grace Charity Laury)',
  'female',
  46.0,
  1,
  0,
  'A/5. 3337',
  13.5,
  nan,
  'S',
  12.325,
  46,
  -32.5,
  'adult'],
 [134,
  1,
  2,
  'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
  'female',
  24.0,
  1,
  0,
  '228414',
  21.0,
  nan,
  'S',
  22.099999999999998,
  45,
  -3.0,
  'adult'],
 [135,
  0,
  2,
  'Sobey, Mr. Samuel James Hayden',
  'male',
  24.0,
  0,
  0,
  'C.A. 29178',
  12.0,
  nan,
  'S',
  11.049999999999999,
  30,
  -12.0,
  'adult'],
 [136,
  0,
  2,
  'Richard, Mr. Emile',
  'male',
  19.0,
  0,
  0,
  'SC/PARIS 2133',
  11.0458,
  nan,
  'C',
  12.788929999999999,
  18,
  -7.9542,
  'adult'],
 [137,
  1,
  1,
  'Newsom, Miss Helen Monypeny',
  'female',
  18.0,
  0,
  2,
  '11752',
  25.2833,
  'D47',
  'S',
  22.340805,
  27,
  7.2833000000000006,
  'adult'],
 [138,
  0,
  1,
  'Futrelle, Mr. Jacques Heath',
  'male',
  32.0,
  1,
  0,
  '113803',
  48.1,
  'C123',
  'S',
  45.135,
  27,
  16.1,
  'adult'],
 [139,
  0,
  3,
  'Osen, Mr. Olaf Elon',
  'male',
  10.0,
  0,
  0,
  '7534',
  3.2166999999999994,
  nan,
  'S',
  7.834194999999999,
  19,
  -6.7833000000000006,
  'child'],
 [140,
  0,
  1,
  'Giglio, Mr. Victor',
  'male',
  21.0,
  0,
  0,
  'PC 17593',
  76.2,
  'B86',
  'C',
  67.32000000000001,
  18,
  55.2,
  'adult'],
 [142,
  1,
  3,
  'Nysten, Miss Anna Sofia',
  'female',
  18.0,
  0,
  0,
  '347081',
  3.75,
  nan,
  'S',
  6.5874999999999995,
  23,
  -14.25,
  'adult'],
 [143,
  1,
  3,
  'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
  'female',
  24.0,
  1,
  0,
  'STON/O2. 3101279',
  15.85,
  nan,
  'S',
  13.4725,
  52,
  -8.15,
  'adult'],
 [144,
  0,
  3,
  'Burke, Mr. Jeremiah',
  'male',
  16.0,
  0,
  0,
  '365222',
  3.75,
  nan,
  'Q',
  5.7375,
  19,
  -12.25,
  'child'],
 [145,
  0,
  2,
  'Andrew, Mr. Edgardo Samuel',
  'male',
  11.0,
  0,
  0,
  '231945',
  4.5,
  nan,
  'S',
  9.775,
  26,
  -6.5,
  'child'],
 [146,
  0,
  2,
  'Nicholls, Mr. Joseph Charles',
  'male',
  17.0,
  1,
  1,
  'C.A. 33112',
  34.75,
  nan,
  'S',
  31.2375,
  28,
  17.75,
  'child'],
 [147,
  1,
  3,
  'Andersson, Mr. August Edvard ("Wennerstrom")',
  'male',
  23.0,
  0,
  0,
  '350043',
  3.7958,
  nan,
  'S',
  6.62643,
  44,
  -19.2042,
  'adult'],
 [148,
  0,
  3,
  'Ford, Miss Robina Maggie "Ruby"',
  'female',
  0.0,
  2,
  2,
  'W./C. 6608',
  25.375,
  nan,
  'S',
  29.21875,
  31,
  25.375,
  'child'],
 [149,
  0,
  2,
  'Navratil, Mr. Michel ("Louis M Hoffman")',
  'male',
  34.5,
  0,
  2,
  '230080',
  24.0,
  'F2',
  'S',
  22.099999999999998,
  40,
  -10.5,
  'adult'],
 [150,
  0,
  2,
  'Byles, Rev. Thomas Roussel Davids',
  'male',
  35.0,
  0,
  0,
  '244310',
  6.0,
  nan,
  'S',
  11.049999999999999,
  33,
  -29.0,
  'adult'],
 [151,
  0,
  2,
  'Bateman, Rev. Robert James',
  'male',
  50.0,
  0,
  0,
  'S.O.P. 1166',
  11.525,
  nan,
  'S',
  10.64625,
  26,
  -38.475,
  'adult'],
 [152,
  1,
  1,
  'Pears, Mrs. Thomas (Edith Wearne)',
  'female',
  19.0,
  1,

In [123]:

s = time.time() # start time to calculate excution time

print(data_list[20])

t = (time.time() - s) * 1e3 #time minus start time
print(round(t, 10), "ms") #print excution time up to 10 decimels

[24, 1, 1, 'Sloper, Mr. William Thompson', 'male', 22.0, 0, 0, '113788', 29.5, 'A6', 'S', 30.175, 28, 7.5, 'adult']
0.6024837494 ms

In [124]:
s = time.time() # start time to calculate excution time

age_list = []
for row in data_list: # loop through rows (lists) in the list
    if row[5] > 60: # age index is 5 in each row
        age_list.append(row) # add row where age > 60 to the new list
print(age_list) 

t = (time.time() - s) * 1e3 #time minus start time
print(round(t, 10), "ms") #print excution time up to 10 decimels

[[34, 0, 2, 'Wheadon, Mr. Edward H', 'male', 63.0, 0, 0, 'C.A. 24579', 7.5, nan, 'S', 8.924999999999999, 21, -55.5, 'adult'], [55, 0, 1, 'Ostby, Mr. Engelhart Cornelius', 'male', 61.0, 0, 1, '113509', 57.9792, 'B30', 'C', 52.68232, 30, -3.0208000000000013, 'adult'], [97, 0, 1, 'Goldschmidt, Mr. George B', 'male', 63.0, 0, 0, 'PC 17754', 26.654200000000003, 'A5', 'C', 29.45607, 25, -36.3458, 'adult'], [117, 0, 3, 'Connors, Mr. Patrick', 'male', 67.5, 0, 0, '370369', 4.75, nan, 'Q', 6.5874999999999995, 20, -62.75, 'adult'], [253, 0, 1, 'Stead, Mr. William Thomas', 'male', 62.0, 0, 0, '113514', 26.55, 'C87', 'S', 22.5675, 25, -35.45, 'adult'], [276, 1, 1, 'Andrews, Miss Kornelia Theodosia', 'female', 61.0, 1, 0, '13502', 75.9583, 'D7', 'S', 66.26455499999999, 32, 14.958299999999994, 'adult'], [457, 0, 1, 'Millet, Mr. Francis Davis', 'male', 61.0, 0, 0, '13509', 22.55, 'E38', 'S', 22.5675, 25, -38.45, 'adult'], [494, 0, 1, 'Artagaveytia, Mr. Ramon', 'male', 70.0, 0, 0, 'PC 17609', 48.5042, nan, 'C', 42.07857, 23, -21.495800000000003, 'senior'], [571, 1, 2, 'Harris, Mr. George', 'male', 62.0, 0, 0, 'S.W./PP 752', 10.5, nan, 'S', 8.924999999999999, 18, -51.5, 'adult'], [626, 0, 1, 'Sutton, Mr. Frederick', 'male', 61.0, 0, 0, '36963', 32.3208, 'D50', 'S', 27.472679999999997, 21, -28.6792, 'adult'], [631, 1, 1, 'Barkworth, Mr. Algernon Henry Wilson', 'male', 80.0, 0, 0, '27042', 30.0, 'A23', 'S', 25.5, 36, -50.0, 'senior'], [673, 0, 2, 'Mitchell, Mr. Henry Michael', 'male', 62.0, 0, 0, 'C.A. 24580', 2.5, nan, 'S', 8.924999999999999, 27, -59.5, 'adult'], [746, 0, 1, 'Crosby, Capt. Edward Gifford', 'male', 68.0, 1, 1, 'WE/P 5735', 69.0, 'B22', 'S', 60.35, 28, 1.0, 'adult'], [852, 0, 3, 'Svensson, Mr. Johan', 'male', 72.0, 0, 0, '347060', 5.775, nan, 'S', 6.608750000000001, 19, -66.225, 'senior']]
1.3728141785 ms

In [125]:
s = time.time() # start time to calculate excution time

age_diff_list = []
sum_age = 0
len_age = 0
for row in data_list: 
    sum_age += row[5] #calulate sum of age values
    len_age +=1 #count number of values
avg = sum_age/len_age #calculate average

for row in data_list: #loop through rows and subtract avg from age values
    row[5] = row[5]- avg
    
    
print(data_list)

t = (time.time() - s) * 1e3 #time minus start time
print(round(t, 10), "ms") #print excution time up to 10 decimels

[[1, 0, 3, 'Braund, Mr. Owen Harris', 'male', -10.2565406162465, 1, 0, 'A/5 21171', 0.25, nan, 'S', 6.1625, 23, -14.75, 'child'], [2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'female', 7.7434593837535, 1, 0, 'PC 17599', 66.2833, 'C85', 'C', 60.590804999999996, 51, 33.2833, 'adult'], [3, 1, 3, 'Heikkinen, Miss Laina', 'female', -0.25654061624650026, 0, 0, 'STON/O2. 3101282', 6.925, nan, 'S', 6.73625, 21, -18.075, 'adult'], [4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female', 1.7434593837534997, 1, 0, '113803', 45.1, 'C123', 'S', 45.135, 44, 18.1, 'adult'], [5, 0, 3, 'Allen, Mr. William Henry', 'male', 4.7434593837535, 0, 0, '373450', 3.0500000000000007, nan, 'S', 6.8425, 24, -26.95, 'adult'], [7, 0, 1, 'McCarthy, Mr. Timothy J', 'male', 26.7434593837535, 0, 0, '17463', 49.8625, 'E46', 'S', 44.083124999999995, 23, -2.137500000000003, 'adult'], [8, 0, 3, 'Palsson, Master Gosta Leonard', 'male', -24.2565406162465, 3, 1, '349909', 20.075, nan, 'S', 17.91375, 29, 19.075, 'child'], [9, 1, 3, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'female', -6.2565406162465, 0, 2, '347742', 3.1333, nan, 'S', 9.463305, 49, -15.8667, 'adult'], [10, 1, 2, 'Nasser, Mrs. Nicholas (Adele Achem)', 'female', -12.2565406162465, 1, 0, '237736', 29.0708, nan, 'C', 25.56018, 35, 16.0708, 'child'], [11, 1, 3, 'Sandstrom, Miss Marguerite Rut', 'female', -21.2565406162465, 1, 1, 'PP 9549', 16.7, 'G6', 'S', 14.194999999999999, 30, 12.7, 'child'], [12, 1, 1, 'Bonnell, Miss Elizabeth', 'female', 32.7434593837535, 0, 0, '113783', 26.55, 'C103', 'S', 22.5675, 23, -31.45, 'adult'], [13, 0, 3, 'Saundercock, Mr. William Henry', 'male', -12.2565406162465, 0, 0, 'A/5. 2151', 1.0500000000000007, nan, 'S', 6.8425, 30, -11.95, 'child'], [14, 0, 3, 'Andersson, Mr. Anders Johan', 'male', 6.7434593837535, 1, 5, '347082', 24.275, nan, 'S', 26.58375, 27, -7.725000000000001, 'adult'], [15, 0, 3, 'Vestrom, Miss Hulda Amanda Adolfina', 'female', -17.2565406162465, 0, 0, '350406', 1.8541999999999996, nan, 'S', 6.676069999999999, 35, -6.1458, 'child'], [16, 1, 2, 'Hewlett, Mrs. (Mary D Kingcome) ', 'female', 29.7434593837535, 0, 0, '248706', 16.0, nan, 'S', 13.6, 32, -39.0, 'adult'], [17, 0, 3, 'Rice, Master Eugene', 'male', -25.2565406162465, 4, 1, '382652', 27.125, nan, 'Q', 24.756249999999998, 19, 27.125, 'child'], [19, 0, 3, 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 'female', -3.2565406162465003, 1, 0, '345763', 9.0, nan, 'S', 15.299999999999999, 55, -13.0, 'adult'], [21, 0, 2, 'Fynney, Mr. Joseph J', 'male', 9.7434593837535, 0, 0, '239865', 26.0, nan, 'S', 22.099999999999998, 20, -9.0, 'adult'], [22, 1, 2, 'Beesley, Mr. Lawrence', 'male', -0.25654061624650026, 0, 0, '248698', 4.0, 'D56', 'S', 11.049999999999999, 21, -21.0, 'adult'], [23, 1, 3, 'McGowan, Miss Anna "Annie"', 'female', -13.2565406162465, 0, 0, '330923', 5.0291999999999994, nan, 'Q', 6.824819999999999, 26, -6.9708000000000006, 'child'], [24, 1, 1, 'Sloper, Mr. William Thompson', 'male', -3.2565406162465003, 0, 0, '113788', 29.5, 'A6', 'S', 30.175, 28, 7.5, 'adult'], [25, 0, 3, 'Palsson, Miss Torborg Danira', 'female', -25.2565406162465, 3, 1, '349909', 13.075, nan, 'S', 17.91375, 28, 13.075, 'child'], [26, 1, 3, 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 'female', 10.7434593837535, 1, 5, '347077', 29.3875, nan, 'S', 26.679375, 57, -6.612500000000001, 'adult'], [28, 0, 1, 'Fortune, Mr. Charles Alexander', 'male', -14.2565406162465, 3, 2, '19950', 255.0, 'C23 C25 C27', 'S', 223.54999999999998, 30, 244.0, 'child'], [31, 0, 1, 'Uruchurtu, Don. Manuel E', 'male', 13.7434593837535, 0, 0, 'PC 17601', 26.7208, nan, 'C', 23.56268, 24, -12.2792, 'adult'], [34, 0, 2, 'Wheadon, Mr. Edward H', 'male', 37.7434593837535, 0, 0, 'C.A. 24579', 7.5, nan, 'S', 8.924999999999999, 21, -55.5, 'adult'], [35, 0, 1, 'Meyer, Mr. Edgar Joseph', 'male', -5.2565406162465, 1, 0, 'PC 17604', 74.1708, nan, 'C', 69.84518, 23, 54.1708, 'adult'], [36, 0, 1, 'Holverson, Mr. Alexander Oskar', 'male', 15.7434593837535, 1, 0, '113789', 51.0, nan, 'S', 44.199999999999996, 30, 10.0, 'adult'], [38, 0, 3, 'Cann, Mr. Ernest Charles', 'male', -10.2565406162465, 0, 0, 'A./5. 2152', 2.0500000000000007, nan, 'S', 6.8425, 24, -12.95, 'child'], [39, 0, 3, 'Vander Planke, Miss Augusta Maria', 'female', -11.2565406162465, 2, 0, '345764', 14.0, nan, 'S', 15.299999999999999, 33, 0.0, 'child'], [40, 1, 3, 'Nicola-Yarred, Miss Jamila', 'female', -13.2565406162465, 1, 0, '2651', 9.2417, nan, 'C', 9.555444999999999, 26, -2.7583, 'child'], [41, 0, 3, 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 'female', 11.7434593837535, 1, 0, '7546', 6.475, nan, 'S', 8.053749999999999, 46, -30.525, 'adult'], [42, 0, 2, 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 'female', -4.2565406162465, 1, 0, '11668', 15.0, nan, 'S', 17.849999999999998, 56, -6.0, 'adult'], [44, 1, 2, 'Laroche, Miss Simonne Marie Anne Andree', 'female', -29.2565406162465, 1, 2, 'SC/Paris 2123', 34.5792, nan, 'C', 35.34232, 39, 38.5792, 'child'], [45, 1, 3, 'Devaney, Miss Margaret Delia', 'female', -13.2565406162465, 0, 0, '330958', 0.8792, nan, 'Q', 6.6973199999999995, 28, -11.1208, 'child'], [50, 0, 3, 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 'female', -7.2565406162465, 1, 0, '349237', 17.8, nan, 'S', 15.13, 45, -0.1999999999999993, 'adult'], [51, 0, 3, 'Panula, Master Juha Niilo', 'male', -24.2565406162465, 4, 1, '3101295', 33.6875, nan, 'S', 33.734375, 25, 32.6875, 'child'], [52, 0, 3, 'Nosworthy, Mr. Richard Cater', 'male', -5.2565406162465, 0, 0, 'A/4. 39886', 6.8, nan, 'S', 6.63, 28, -13.2, 'adult'], [53, 1, 1, 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'female', 18.7434593837535, 1, 0, 'PC 17572', 71.7292, 'D33', 'C', 65.21982, 40, 27.729200000000006, 'adult'], [54, 1, 2, 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 'female', -3.2565406162465003, 1, 0, '2926', 19.0, nan, 'S', 22.099999999999998, 50, -3.0, 'adult'], [55, 0, 1, 'Ostby, Mr. Engelhart Cornelius', 'male', 35.7434593837535, 0, 1, '113509', 57.9792, 'B30', 'C', 52.68232, 30, -3.0208000000000013, 'adult'], [57, 1, 2, 'Rugg, Miss Emily', 'female', -11.2565406162465, 0, 0, 'C.A. 31026', 3.5, nan, 'S', 8.924999999999999, 16, -10.5, 'child'], [58, 0, 3, 'Novel, Mr. Mansouer', 'male', -3.7565406162465003, 0, 0, '2697', 0.22919999999999963, nan, 'C', 6.144819999999999, 19, -21.2708, 'adult'], [59, 1, 2, 'West, Miss Constance Mirium', 'female', -23.2565406162465, 1, 2, 'C.A. 34651', 24.75, nan, 'S', 23.5875, 27, 22.75, 'child'], [60, 0, 3, 'Goodwin, Master William Frederick', 'male', -16.2565406162465, 5, 2, 'CA 2144', 44.9, nan, 'S', 39.864999999999995, 33, 35.9, 'child'], [61, 0, 3, 'Sirayanian, Mr. Orsen', 'male', -8.2565406162465, 0, 0, '2669', 2.2291999999999996, nan, 'C', 6.144819999999999, 21, -14.770800000000001, 'child'], [62, 1, 1, 'Icard, Miss Amelie', 'female', 5.7434593837535, 0, 0, '113572', 73.0, 'B28', nan, 68.0, 18, 42.0, 'adult'], [63, 0, 1, 'Harris, Mr. Henry Birkhardt', 'male', 14.7434593837535, 1, 0, '36973', 78.475, 'C83', 'S', 70.95375, 27, 38.474999999999994, 'adult'], [64, 0, 3, 'Skoog, Master Harald', 'male', -26.2565406162465, 3, 2, '347088', 22.9, nan, 'S', 23.715, 20, 23.9, 'child'], [67, 1, 2, 'Nye, Mrs. (Elizabeth Ramell)', 'female', 3.7434593837534997, 0, 0, 'C.A. 29395', 10.5, 'F33', 'S', 8.924999999999999, 28, -18.5, 'adult'], [68, 0, 3, 'Crease, Mr. Ernest James', 'male', -9.2565406162465, 0, 0, 'S.P. 3464', 5.1583000000000006, nan, 'S', 6.9345550000000005, 24, -10.8417, 'child'], [69, 1, 3, 'Andersson, Miss Erna Alexandra', 'female', -10.2565406162465, 4, 2, '3101281', 5.925, nan, 'S', 6.73625, 30, -9.075, 'child'], [70, 0, 3, 'Kink, Mr. Vincenz', 'male', -8.2565406162465, 2, 0, '315151', -0.33750000000000036, nan, 'S', 7.363124999999999, 17, -17.3375, 'child'], [71, 0, 2, 'Jenkin, Mr. Stephen Curnow', 'male', 4.7434593837535, 0, 0, 'C.A. 33111', 8.5, nan, 'S', 8.924999999999999, 26, -21.5, 'adult'], [72, 0, 3, 'Goodwin, Miss Lillian Amy', 'female', -11.2565406162465, 5, 2, 'CA 2144', 44.9, nan, 'S', 39.864999999999995, 25, 30.9, 'child'], [73, 0, 2, 'Hood, Mr. Ambrose Jr', 'male', -12.2565406162465, 0, 0, 'S.O.C. 14879', 65.5, nan, 'S', 62.475, 20, 52.5, 'child'], [74, 0, 3, 'Chronopoulos, Mr. Apostolos', 'male', -6.2565406162465, 1, 0, '2680', 7.4542, nan, 'C', 12.28607, 27, -11.5458, 'adult'], [75, 1, 3, 'Bing, Mr. Lee', 'male', 1.7434593837534997, 0, 0, '1601', 51.4958, nan, 'S', 48.02143, 13, 24.495800000000003, 'adult'], [76, 0, 3, 'Moen, Mr. Sigurd Hansen', 'male', -5.2565406162465, 0, 0, '348123', 2.6500000000000004, 'F G73', 'S', 6.5025, 23, -17.35, 'adult'], [79, 1, 2, 'Caldwell, Master Alden Gates', 'male', -24.426540616246502, 0, 2, '248738', 29.0, nan, 'S', 24.65, 28, 28.17, 'child'], [80, 1, 3, 'Dowdell, Miss Elizabeth', 'female', 0.7434593837534997, 0, 0, '364516', 8.475, nan, 'S', 10.60375, 23, -17.525, 'adult'], [81, 0, 3, 'Waelens, Mr. Achille', 'male', -3.2565406162465003, 0, 0, '345767', 9.0, nan, 'S', 7.6499999999999995, 20, -13.0, 'adult'], [82, 1, 3, 'Sheerlinck, Mr. Jan Baptist', 'male', -3.2565406162465003, 0, 0, '345779', 2.5, nan, 'S', 8.075, 27, -19.5, 'adult'], [84, 0, 1, 'Carrau, Mr. Francisco M', 'male', 1.7434593837534997, 0, 0, '113059', 46.1, nan, 'S', 40.035000000000004, 23, 19.1, 'adult'], [85, 1, 2, 'Ilett, Miss Bertha', 'female', -8.2565406162465, 0, 0, 'SO/C 14885', 10.5, nan, 'S', 8.924999999999999, 18, -6.5, 'child'], [86, 1, 3, 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 'female', -0.25654061624650026, 3, 0, '3101278', 7.85, nan, 'S', 13.4725, 55, -17.15, 'adult'], [87, 0, 3, 'Ford, Mr. William Neal', 'male', -17.2565406162465, 1, 3, 'W./C. 6608', 26.375, nan, 'S', 29.21875, 22, 18.375, 'child'], [89, 1, 1, 'Fortune, Miss Mabel Helen', 'female', -10.2565406162465, 3, 2, '19950', 255.0, 'C23 C25 C27', 'S', 223.54999999999998, 25, 240.0, 'child'], [90, 0, 3, 'Celotti, Mr. Francesco', 'male', -8.2565406162465, 0, 0, '343275', 1.0500000000000007, nan, 'S', 6.8425, 22, -15.95, 'child'], [91, 0, 3, 'Christmann, Mr. Emil', 'male', -0.25654061624650026, 0, 0, '343276', 4.050000000000001, nan, 'S', 6.8425, 20, -20.95, 'adult'], [92, 0, 3, 'Andreasson, Mr. Paul Edvin', 'male', -13.2565406162465, 0, 0, '347466', -0.14580000000000037, nan, 'S', 6.676069999999999, 26, -12.145800000000001, 'child'], [93, 0, 1, 'Chaffee, Mr. Herbert Fuller', 'male', 14.7434593837535, 1, 0, 'W.E.P. 5734', 55.175, 'E31', 'S', 51.998749999999994, 27, 15.174999999999997, 'adult'], [94, 0, 3, 'Dean, Mr. Bertram Frank', 'male', -7.2565406162465, 1, 2, 'C.A. 2315', 12.575, nan, 'S', 17.48875, 23, -5.425000000000001, 'adult'], [95, 0, 3, 'Coxon, Mr. Daniel', 'male', 25.7434593837535, 0, 0, '364500', -0.75, nan, 'S', 6.1625, 17, -51.75, 'adult'], [97, 0, 1, 'Goldschmidt, Mr. George B', 'male', 37.7434593837535, 0, 0, 'PC 17754', 26.654200000000003, 'A5', 'C', 29.45607, 25, -36.3458, 'adult'], [98, 1, 1, 'Greenfield, Mr. William Bertram', 'male', -7.2565406162465, 0, 1, 'PC 17759', 58.3583, 'D10 D12', 'C', 53.854555, 31, 40.3583, 'adult'], [99, 1, 2, 'Doling, Mrs. John T (Ada Julia Bone)', 'female', 3.7434593837534997, 0, 1, '231919', 18.0, nan, 'S', 19.55, 36, -11.0, 'adult'], [100, 0, 2, 'Kantor, Mr. Sinai', 'male', 1.7434593837534997, 1, 0, '244367', 19.0, nan, 'S', 22.099999999999998, 17, -8.0, 'adult'], [101, 0, 3, 'Petranec, Miss Matilda', 'female', -2.2565406162465003, 0, 0, '349245', 2.8958000000000004, nan, 'S', 6.71143, 22, -20.1042, 'adult'], [103, 0, 1, 'White, Mr. Richard Frasar', 'male', -4.2565406162465, 0, 1, '35281', 77.2875, 'D26', 'S', 65.694375, 25, 56.287499999999994, 'adult'], [104, 0, 3, 'Johansson, Mr. Gustaf Joel', 'male', -1.2565406162465003, 0, 0, '7540', -0.34580000000000055, nan, 'S', 7.356069999999999, 26, -24.3458, 'adult'], [105, 0, 3, 'Gustafsson, Mr. Anders Vilhelm', 'male', 2.7434593837534997, 2, 0, '3101276', -1.0750000000000002, nan, 'S', 6.73625, 30, -29.075, 'adult'], [106, 0, 3, 'Mionoff, Mr. Stoytcho', 'male', -5.2565406162465, 0, 0, '349207', -0.10419999999999963, nan, 'S', 6.71143, 21, -20.1042, 'adult'], [107, 1, 3, 'Salkjelsvik, Miss Anna Kristine', 'female', -5.2565406162465, 0, 0, '343120', 6.65, nan, 'S', 6.5025, 31, -13.35, 'adult'], [109, 0, 3, 'Rekic, Mr. Tido', 'male', 9.7434593837535, 0, 0, '349249', 4.8958, nan, 'S', 6.71143, 15, -30.1042, 'adult'], [111, 0, 1, 'Porter, Mr. Walter Chamberlain', 'male', 17.7434593837535, 0, 0, '110465', 48.0, 'C110', 'S', 44.199999999999996, 30, 5.0, 'adult'], [112, 0, 3, 'Zabour, Miss Hileni', 'female', -18.7565406162465, 1, 0, '2665', 6.4542, nan, 'C', 12.28607, 19, -0.04579999999999984, 'child'], [113, 0, 3, 'Barton, Mr. David John', 'male', -5.2565406162465, 0, 0, '324669', 6.050000000000001, nan, 'S', 6.8425, 22, -13.95, 'adult'], [114, 0, 3, 'Jussila, Miss Katriina', 'female', -11.2565406162465, 1, 0, '4136', 3.8249999999999993, nan, 'S', 8.351249999999999, 22, -10.175, 'child'], [115, 0, 3, 'Attalah, Miss Malake', 'female', -11.2565406162465, 0, 0, '2627', 11.4583, nan, 'C', 12.289555, 20, -2.5417000000000005, 'child'], [116, 0, 3, 'Pekoniemi, Mr. Edvard', 'male', -5.2565406162465, 0, 0, 'STON/O 2. 3101294', 6.925, nan, 'S', 6.73625, 21, -13.075, 'adult'], [117, 0, 3, 'Connors, Mr. Patrick', 'male', 42.2434593837535, 0, 0, '370369', 4.75, nan, 'Q', 6.5874999999999995, 20, -62.75, 'adult'], [118, 0, 2, 'Turpin, Mr. William John Robert', 'male', -1.2565406162465003, 1, 0, '11668', 16.0, nan, 'S', 17.849999999999998, 31, -8.0, 'adult'], [119, 0, 1, 'Baxter, Mr. Quigg Edmond', 'male', -10.2565406162465, 0, 1, 'PC 17558', 238.5208, 'B58 B60', 'C', 210.39268, 24, 223.5208, 'child'], [120, 0, 3, 'Andersson, Miss Ellis Anna Maria', 'female', -26.2565406162465, 4, 2, '347082', 28.275, nan, 'S', 26.58375, 32, 29.275, 'child'], [121, 0, 2, 'Hickman, Mr. Stanley George', 'male', -9.2565406162465, 2, 0, 'S.O.C. 14879', 68.5, nan, 'S', 62.475, 27, 52.5, 'child'], [123, 0, 2, 'Nasser, Mr. Nicholas', 'male', 6.2434593837535, 1, 0, '237736', 29.0708, nan, 'C', 25.56018, 20, -2.4292000000000016, 'adult'], [124, 1, 2, 'Webber, Miss Susan', 'female', 0.24345938375349974, 0, 0, '27267', 6.0, 'E101', 'S', 11.049999999999999, 18, -19.5, 'adult'], [125, 0, 1, 'White, Mr. Percival Wayland', 'male', 22.7434593837535, 0, 1, '35281', 71.2875, 'D26', 'S', 65.694375, 27, 23.287499999999994, 'adult'], [126, 1, 3, 'Nicola-Yarred, Master Elias', 'male', -15.2565406162465, 1, 0, '2651', 9.2417, nan, 'C', 9.555444999999999, 27, -0.7583000000000002, 'child'], [128, 1, 3, 'Madsen, Mr. Fridtjof Arne', 'male', -6.2565406162465, 0, 0, 'C 17369', 2.1417, nan, 'S', 6.070445, 25, -16.8583, 'adult'], [130, 0, 3, 'Ekstrom, Mr. Johan', 'male', 14.7434593837535, 0, 0, '347061', 1.9749999999999996, nan, 'S', 5.92875, 18, -38.025, 'adult'], [131, 0, 3, 'Drazenoic, Mr. Jozef', 'male', 6.7434593837535, 0, 0, '349241', 6.8958, nan, 'C', 6.71143, 20, -25.1042, 'adult'], [132, 0, 3, 'Coelho, Mr. Domingos Fernandeo', 'male', -6.2565406162465, 0, 0, 'SOTON/O.Q. 3101307', 6.05, nan, 'S', 5.9925, 30, -12.95, 'adult'], [133, 0, 3, 'Robins, Mrs. Alexander A (Grace Charity Laury)', 'female', 20.7434593837535, 1, 0, 'A/5. 3337', 13.5, nan, 'S', 12.325, 46, -32.5, 'adult'], [134, 1, 2, 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 'female', -1.2565406162465003, 1, 0, '228414', 21.0, nan, 'S', 22.099999999999998, 45, -3.0, 'adult'], [135, 0, 2, 'Sobey, Mr. Samuel James Hayden', 'male', -1.2565406162465003, 0, 0, 'C.A. 29178', 12.0, nan, 'S', 11.049999999999999, 30, -12.0, 'adult'], [136, 0, 2, 'Richard, Mr. Emile', 'male', -6.2565406162465, 0, 0, 'SC/PARIS 2133', 11.0458, nan, 'C', 12.788929999999999, 18, -7.9542, 'adult'], [137, 1, 1, 'Newsom, Miss Helen Monypeny', 'female', -7.2565406162465, 0, 2, '11752', 25.2833, 'D47', 'S', 22.340805, 27, 7.2833000000000006, 'adult'], [138, 0, 1, 'Futrelle, Mr. Jacques Heath', 'male', 6.7434593837535, 1, 0, '113803', 48.1, 'C123', 'S', 45.135, 27, 16.1, 'adult'], [139, 0, 3, 'Osen, Mr. Olaf Elon', 'male', -15.2565406162465, 0, 0, '7534', 3.2166999999999994, nan, 'S', 7.834194999999999, 19, -6.7833000000000006, 'child'], [140, 0, 1, 'Giglio, Mr. Victor', 'male', -4.2565406162465, 0, 0, 'PC 17593', 76.2, 'B86', 'C', 67.32000000000001, 18, 55.2, 'adult'], [142, 1, 3, 'Nysten, Miss Anna Sofia', 'female', -7.2565406162465, 0, 0, '347081', 3.75, nan, 'S', 6.5874999999999995, 23, -14.25, 'adult'], [143, 1, 3, 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', 'female', -1.2565406162465003, 1, 0, 'STON/O2. 3101279', 15.85, nan, 'S', 13.4725, 52, -8.15, 'adult'], [144, 0, 3, 'Burke, Mr. Jeremiah', 'male', -9.2565406162465, 0, 0, '365222', 3.75, nan, 'Q', 5.7375, 19, -12.25, 'child'], [145, 0, 2, 'Andrew, Mr. Edgardo Samuel', 'male', -14.2565406162465, 0, 0, '231945', 4.5, nan, 'S', 9.775, 26, -6.5, 'child'], [146, 0, 2, 'Nicholls, Mr. Joseph Charles', 'male', -8.2565406162465, 1, 1, 'C.A. 33112', 34.75, nan, 'S', 31.2375, 28, 17.75, 'child'], [147, 1, 3, 'Andersson, Mr. August Edvard ("Wennerstrom")', 'male', -2.2565406162465003, 0, 0, '350043', 3.7958, nan, 'S', 6.62643, 44, -19.2042, 'adult'], [148, 0, 3, 'Ford, Miss Robina Maggie "Ruby"', 'female', -25.2565406162465, 2, 2, 'W./C. 6608', 25.375, nan, 'S', 29.21875, 31, 25.375, 'child'], [149, 0, 2, 'Navratil, Mr. Michel ("Louis M Hoffman")', 'male', 9.2434593837535, 0, 2, '230080', 24.0, 'F2', 'S', 22.099999999999998, 40, -10.5, 'adult'], [150, 0, 2, 'Byles, Rev. Thomas Roussel Davids', 'male', 9.7434593837535, 0, 0, '244310', 6.0, nan, 'S', 11.049999999999999, 33, -29.0, 'adult'], [151, 0, 2, 'Bateman, Rev. Robert James', 'male', 24.7434593837535, 0, 0, 'S.O.P. 1166', 11.525, nan, 'S', 10.64625, 26, -38.475, 'adult'], [152, 1, 1, 'Pears, Mrs. Thomas (Edith Wearne)', 'female', -6.2565406162465, 1, 0, '113776', 63.599999999999994, 'C2', 'S', 56.60999999999999, 33, 44.599999999999994, 'adult'], [153, 0, 3, 'Meo, Mr. Alfonzo', 'male', 26.2434593837535, 0, 0, 'A.5. 11206', 4.050000000000001, nan, 'S', 6.8425, 16, -47.45, 'adult'], [154, 0, 3, 'van Billiard, Mr. Austin Blyler', 'male', 15.2434593837535, 0, 2, 'A/5. 851', 14.5, nan, 'S', 12.325, 31, -26.0, 'adult'], [156, 0, 1, 'Williams, Mr. Charles Duane', 'male', 23.7434593837535, 0, 1, 'PC 17597', 59.3792, nan, 'C', 52.17232, 27, 10.379199999999997, 'adult'], [157, 1, 3, 'Gilnagh, Miss Katherine "Katie"', 'female', -10.2565406162465, 0, 0, '35851', 6.7333, nan, 'Q', 6.5733049999999995, 31, -8.2667, 'child'], [158, 0, 3, 'Corn, Mr. Harry', 'male', -4.2565406162465, 0, 0, 'SOTON/OQ 392090', -0.9499999999999993, nan, 'S', 6.8425, 15, -21.95, 'adult'], [161, 0, 3, 'Cribb, Mr. John Hatfield', 'male', 12.7434593837535, 0, 1, '371362', 10.100000000000001, nan, 'S', 13.685, 24, -27.9, 'adult'], [162, 1, 2, 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)', 'female', 13.7434593837535, 0, 0, 'C.A. 33595', 14.75, nan, 'S', 13.3875, 50, -24.25, 'adult'], [163, 0, 3, 'Bengtsson, Mr. John Viktor', 'male', -1.2565406162465003, 0, 0, '347068', 5.775, nan, 'S', 6.608750000000001, 26, -18.225, 'adult'], [164, 0, 3, 'Calic, Mr. Jovo', 'male', -10.2565406162465, 0, 0, '315093', 6.6625, nan, 'S', 7.363124999999999, 15, -8.3375, 'child'], [165, 0, 3, 'Panula, Master Eino Viljami', 'male', -27.2565406162465, 4, 1, '3101295', 36.6875, nan, 'S', 33.734375, 27, 38.6875, 'child'], [166, 1, 3, 'Goldsmith, Master Frank John William "Frankie"', 'male', -23.2565406162465, 0, 2, '363291', 13.524999999999999, nan, 'S', 17.44625, 46, 11.524999999999999, 'child'], [168, 0, 3, 'Skoog, Mrs. William (Anna Bernhardina Karlsson)', 'female', 13.7434593837535, 1, 4, '347088', 21.9, nan, 'S', 23.715, 47, -17.1, 'adult'], [170, 0, 3, 'Ling, Mr. Lee', 'male', 2.7434593837534997, 0, 0, '1601', 56.4958, nan, 'S', 48.02143, 13, 28.495800000000003, 'adult'], [171, 0, 1, 'Van der hoef, Mr. Wyckoff', 'male', 26.7434593837535, 0, 0, '111240', 24.5, 'B19', 'S', 28.474999999999998, 25, -27.5, 'adult'], [172, 0, 3, 'Rice, Master Arthur', 'male', -30.2565406162465, 4,